# path:
save_img_path: "./sample_videos/t2i-"
pretrained_model_path: "maxin-cn/LatteT2V"

# model config: 
# maxin-cn/Latte-0: the first released version
# maxin-cn/Latte-1: the second version with better performance (released on May. 23, 2024)
model: LatteT2V
video_length: 1
image_size: [512, 512]
# # beta schedule
beta_start: 0.0001
beta_end: 0.02
beta_schedule: "linear"
variance_type: "learned_range"

# model speedup
use_compile: False
use_fp16: True

# sample config:
seed:
run_time: 0
guidance_scale: 7.5
sample_method: 'DDIM'
num_sampling_steps: 50
enable_temporal_attentions: True # LatteT2V-V0: set to False; LatteT2V-V1: set to True
enable_vae_temporal_decoder: False

text_prompt: [
              'Yellow and black tropical fish dart through the sea.',
              'An epic tornado attacking above aglowing city at night.',
              'Slow pan upward of blazing oak fire in an indoor fireplace.',
              'a cat wearing sunglasses and working as a lifeguard at pool.',
              'Sunset over the sea.',
              'A dog in astronaut suit and sunglasses floating in space.',
              ]